### ISSUE TITLE
Documentation lacks direct "Edit on Github" link

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-docs#167]
For open source projects and documentation frameworks, the best practice is backlink each individual document page to their Github source, so that drive-by developers can easily update documentation.

E.g.

- "Edit on Github" on Sphinx
- "Edit on Github" on MkDocs (GitBook)

I did not see such links in `docs.elrond.com`. Is this planned, as it might significantly bring down the barrier to contribute to the documentation?

**Comment by tredondo** [comment]
This is not just a great idea, but a "duh" / best practice one. A bit stupefying that an <kbd>Edit</kbd> link hasn't been implemented already.

> Is this planned, as it might significantly bring down the barrier to contribute to the documentation?

Given [how long it took for a trivial PR to get merged](https://github.com/ElrondNetwork/docs.elrond.com/pull/232#event-5905648365), it doesn't seem that much value is placed on accepting contributions via GitHub. I've seen this pattern in many other OSS crypto projects, and I struggle to understand its cause. Development takes place on Discord? Crypto devs inexperienced with how OSS is developed on GitHub? Beats me. 🤷🏻‍♂️  Even silly web component libraries are better managed on GitHub than many crypto projects that move billions of dollars.

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. This is, indeed, a very good suggestion. We will handle it in the next version of the docs, where we plan to use a more robust solution that will easily allow us to add this feature.
