### ISSUE TITLE
Overview lacks "Why" for smart contract developers

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-docs#169]
Elrond Network overview clearly describes what Elrond does:

https://docs.elrond.com/validators/overview/

However it lacks "Why" - the target audience is smart contract developers and this audience is not addressed well in this overview - why to develop on Elrond (vs. something else).

**Comment by bogdan-rosianu** [comment]
Hello! This page has changed since this issue has been open. The page focuses on validators only. The "smart contract developers audience" is described in the Developers section. Can you analyze it again and close the issue if no longer relevant?

**Comment by schimih** [comment]
Closing issue because:

- https://docs.multiversx.com/developers/overview has changed since the issue has been open;
- added https://docs.multiversx.com/developers/overview as well.
