### ISSUE TITLE
The Hello World example is in C

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-docs#170]
The first example the developers encounter is written in C.

https://docs.elrond.com/developers/tutorials/counter/

This is counter-intutitive because we assume most of if not all Elrond smart contracts should be written in Rust.

**Comment by schimih** [comment]
Hey @miohtama ,
I will close this issue as long as the counter tutorial will stay as it is.
We will add many other tutorials in Rust, this year.
Thanks!
