### ISSUE TITLE
Elrond config scripts page is messy, poorly understandable and dangerous

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-docs#174]
The config script page is here:

https://docs.elrond.com/validators/mainnet/config-scripts/

While the goal states "streamlining", this page has many issues that are opposite of this goal.

* It asks user to figure out its username and host name (these are available to any shell script)

* It asks user to hand edit config file (could be autogenerated)

* It asks user to give `sudo` permission to a random stuff downloaded from Github, a matter that any security expert would say is critically dangerous

Suggestion

Design the scripts so that none of this is needed. If necessary, look other projects for inspiration how this can be done without developer experience usability issues like above.

**Comment by schimih** [comment]
Solved the issue with:
https://docs.multiversx.com/validators/nodes-scripts/config-scripts/

Please let us know if we should reopen or create a new issue. :pray:
