### ISSUE TITLE
Link to example NestJS microservice is invalid in tutorial

### ISSUE THREAD

**Issue by getlarge** [multiversx/mx-docs#601]
The link [here](https://github.com/multiversx/mx-docs/blob/main/docs/developers/tutorials/your-first-microservice.md?plain=1#L80) point to the example smart contract, whereas it should probably lead to [ping pong service](https://github.com/multiversx/mx-ping-pong-service).

**Comment by schimih** [comment]
Hey @getlarge 

Thanks for your input. It will be fixed by #604 .

Therefore I will close it. :pray:
