### ISSUE TITLE
ROF-c85ab7 LOGO 

### ISSUE THREAD

**Issue by raznaoficial** [multiversx/mx-docs#698]
![IMG_3380](https://github.com/multiversx/mx-docs/assets/103883035/e743027c-4135-4f40-a079-741be2229476)
![IMG_3381](https://github.com/multiversx/mx-docs/assets/103883035/bf0994b4-2da4-4f6d-8e73-bea51c59e7ee)

ROF-c85ab7

I'm trying to put a logo on the ROF token 
can anyone help?

**Comment by bogdan-rosianu** [comment]
Hi. Please refer to the `mx-assets` repository: https://github.com/multiversx/mx-assets
